---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media
  namespace: paperless-ngx
spec:
  resources:
    requests:
      storage: 20G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: paperless-ngx
spec:
  resources:
    requests:
      storage: 5G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
