---
- name: "Prepare Longhorn deployment"
  hosts: all
  become: true
  tasks:
    - name: "Install iscsid"
      ansible.builtin.package:
        name: "iscsi-initiator-utils"
        state: "present"

    - name: "Set initiatorname"
      ansible.builtin.shell:
        cmd: "echo \"InitiatorName=$(/sbin/iscsi-iname)\" > /etc/iscsi/initiatorname.iscsi"

    - name: "Enable and start iscsid"
      ansible.builtin.systemd:
        name: "iscsid"
        enabled: true
        state: "started"
